FROM wcahuaya/ubuntu-javita
LABEL MAINTAINER Willian Cahuaya <wcahuayaramos@gmail.com>
EXPOSE 8765
ADD onlinesale-msdiscoverserver.jar onlinesale-msdiscoverserver.jar
ENTRYPOINT ["java", "-jar", "onlinesale-msdiscoverserver.jar"]


