server:
  port: 8081
  servlet:
    context-path: /ctxpath-ms-businessquery

spring:
  application:
    name: appname-ms-businessquery
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/