server:
  port: 8081
  servlet:
    context-path: /ms-businessquery

spring:
  application:
    name: msbusinessquery
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka