server:
  port: 8092
  servlet:
    context-path: /ctxpath-ms-busquery

spring:
  application:
    name: appname-ms-busquery

#ms-consulta.ribbon.listOfServers=http://localhost:8081, http://localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.241.129:8765/ctxpath-ms-discoverserver/eureka/
