server:
  port: 8761
  servlet:
    context-path: /ctxpath-ms-discoverserver

spring:
  application:
    name: appname-ms-discoverserver
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    peer-node-read-timeout-ms: 6000