server:
  port: 8755
  #servlet:
    #context-path: /ctxpath-ms-apigateway  #(Mustn't register)

spring:
  application:
    name: appname-ms-apigateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/ctxpath-ms-discoverserver/eureka/