server:
  port: 8765
  #servlet:
    #context-path: /ctxpath-ms-apigateway  #(Mustn't register)

spring:
  application:
    name: appname-ms-apigateway

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/