DROP TABLE IF EXISTS schmicroservices.TBL_CLIENT_PRODUCT;
DROP TABLE IF EXISTS schmicroservices.TBL_PRODUCT;
DROP TABLE IF EXISTS schmicroservices.TBL_CLIENT;
DROP TABLE IF EXISTS schmicroservices.TBL_COMPANY;

DROP SEQUENCE IF EXISTS schmicroservices."SEQ_TBL_CLIENT_PRODUCT";
DROP SEQUENCE IF EXISTS schmicroservices."SEQ_TBL_PRODUCT";
DROP SEQUENCE IF EXISTS schmicroservices."SEQ_TBL_CLIENT";
DROP SEQUENCE IF EXISTS schmicroservices."SEQ_TBL_COMPANY";

CREATE SEQUENCE schmicroservices."SEQ_TBL_CLIENT_PRODUCT"
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 99999
   CACHE 1;
ALTER SEQUENCE schmicroservices."SEQ_TBL_CLIENT_PRODUCT" OWNER TO postgres;

CREATE SEQUENCE schmicroservices."SEQ_TBL_PRODUCT"
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 99999
   CACHE 1;
ALTER SEQUENCE schmicroservices."SEQ_TBL_PRODUCT" OWNER TO postgres;

CREATE SEQUENCE schmicroservices."SEQ_TBL_CLIENT"
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 99999
   CACHE 1;
ALTER SEQUENCE schmicroservices."SEQ_TBL_CLIENT" OWNER TO postgres;

CREATE SEQUENCE schmicroservices."SEQ_TBL_COMPANY"
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 99999
   CACHE 1;
ALTER SEQUENCE schmicroservices."SEQ_TBL_COMPANY" OWNER TO postgres;