server:
  port: 8761
  servlet:
    context-path: /ms-eurekaserver

spring:
  application:
    name: eurekaserver
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    peer-node-read-timeout-ms: 6000